# Generated by Django 3.2.3 on 2021-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('district', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('subjects', models.CharField(max_length=100)),
                ('num_student', models.IntegerField(help_text='số lượng học sinh')),
                ('date_start', models.DateTimeField(verbose_name='Ngày khai giảng')),
                ('level', models.CharField(max_length=20)),
                ('fee_expected', models.IntegerField()),
                ('frequency', models.IntegerField(default=2)),
                ('teaching_time', models.CharField(max_length=500)),
                ('sex_require', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
    ]
