# Generated by Django 3.2.3 on 2021-06-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_info',
            name='district',
            field=models.CharField(blank=True, choices=[('D1', 'Quận 1'), ('D2', 'Quận 2'), ('D3', 'Quận 3'), ('D4', 'Quận 4'), ('D5', 'Quận 5'), ('D6', 'Quận 6'), ('D7', 'Quận 7'), ('D8', 'Quận 8'), ('D10', 'Quận 10'), ('D11', 'Quận 11'), ('D12', 'Quận 12'), ('BC', 'Bình Chánh'), ('BTan', 'Bình Tân'), ('BThanh', 'Bình Thạnh'), ('CG', 'Cần Giờ '), ('CC', 'Củ Chi'), ('HM', 'Hóc Môn'), ('NB', 'Nhà Bè'), ('PN', 'Phú Nhuận'), ('TP', 'Tân Phú'), ('TB', 'Tân Bình'), ('TD', 'Thủ Đức')], max_length=10),
        ),
    ]
