# Generated by Django 3.2.3 on 2021-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210602_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_info',
            name='note',
            field=models.TextField(default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Địa chỉ Email'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='fee_expected',
            field=models.IntegerField(verbose_name='Mức lương'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='frequency',
            field=models.IntegerField(default=2, verbose_name='Số buổi/Tuần'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='level',
            field=models.CharField(max_length=20, verbose_name='Lớp'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='num_student',
            field=models.IntegerField(verbose_name='Số lượng học sinh'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='sex_require',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('both', 'Cả hai')], default='male', max_length=10, verbose_name='Yêu cầu về giới tính'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='subjects',
            field=models.CharField(max_length=100, verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='class_info',
            name='teaching_time',
            field=models.CharField(help_text='VD: Tối 2-4-6, 18h', max_length=500, verbose_name='Thời gian dạy'),
        ),
    ]
