# Generated by Django 3.2.3 on 2021-06-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210602_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='tuitor_info',
            fields=[
                ('tuitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('address', models.CharField(max_length=254, verbose_name='Địa chỉ')),
                ('year_birthday', models.CharField(help_text='Năm Sinh', max_length=4, verbose_name='Năm sinh')),
                ('sex', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('both', 'Cả hai')], default='male', max_length=10, verbose_name='Giới tính')),
                ('id_number', models.CharField(max_length=12, verbose_name='CMND/CCCD')),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('level', models.CharField(choices=[('student', 'Sinh viên giỏi'), ('teacher', 'Giáo viên đứng lớp'), ('teacher2', 'Giáo viên tự do'), ('lecturer', 'Giảng viên đại học'), ('master', 'Thạc sĩ')], default='lecturer', max_length=10, verbose_name='Trình độ')),
                ('work_place', models.CharField(help_text='Nơi đang học hoặc nơi giảng dạy', max_length=200, verbose_name='Nơi công tác')),
                ('major', models.CharField(max_length=254, verbose_name='Chuyên ngành')),
                ('describe', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
