# Generated by Django 3.2.3 on 2021-06-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tuitor_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='class_info',
            new_name='ClassInfo',
        ),
        migrations.RenameModel(
            old_name='tuitor_info',
            new_name='TuitorInfo',
        ),
    ]
