 # Generated by Django 3.2.3 on 2021-06-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tuitorinfo_year_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassInfo',
        ),
    ]
