# Generated by Django 3.2.3 on 2021-06-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_alter_classinfo_fee_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='level',
            field=models.CharField(blank=True, choices=[(None, 'Chương trình học mong muốn'), ('tieuhoc', 'Chương trình Tiểu học'), ('thcs', 'Chương trình Trung Học Cơ Sở'), ('thpt', 'Chương trình Trung Học Phổ Thông'), ('ct_quocte', 'Chương trình Quốc Tế'), ('gd_tienganh', 'DẠY BẰNG TIẾNG ANH CÁC MÔN TOÁN-LÝ-HÓA '), ('gd_canban', 'DẠY CĂN BẢN CÁC MÔN TOÁN-LÝ-HÓA'), ('lt_sat', 'LUYỆN THI SAT'), ('lt_trandainghia', 'LUYỆN THI VÀO LỚP 6 TRẦN ĐẠI NGHĨA'), ('lt_lop10', 'LUYỆN THI VÀO LỚP 10 TRƯỜNG CHUYÊN / CÔNG LẬP'), ('lt_daihoc', 'LUYỆN THI ĐẠI HỌC'), ('ielts', 'IELTS Cơ bản'), ('khac', 'Khác')], max_length=26, verbose_name='Lớp'),
        ),
    ]
