# Generated by Django 3.2.3 on 2021-06-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_classinfo_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='sex_require',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('both', 'Khác')], max_length=10, verbose_name='Yêu cầu về giới tính'),
        ),
    ]
