# Generated by Django 3.2.3 on 2021-06-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_alter_classinfo_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='sex_require',
            field=models.CharField(choices=[(None, 'Yêu cầu về giới tính người dạy'), ('male', 'Nam'), ('female', 'Nữ'), ('both', 'Khác')], default='both', max_length=10, verbose_name='Yêu cầu về giới tính'),
        ),
    ]
