# Generated by Django 3.2.3 on 2021-06-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_alter_classinfo_sex_require'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Đã xác nhận với phụ huynh ? ', verbose_name='Đã xác nhận'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='sex_require',
            field=models.CharField(choices=[(None, 'Yêu cầu về giới tính người dạy'), ('male', 'Nam'), ('female', 'Nữ'), ('both', 'Khác')], max_length=10, verbose_name='Yêu cầu về giới tính'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='status',
            field=models.BooleanField(default=False, help_text='Đang dạy(tick)/Ngưng dạy(untick)', verbose_name='Trạng Thái lớp'),
        ),
    ]
