# Generated by Django 3.2.3 on 2021-06-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_auto_20210612_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='student_info',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Thông tin học sinh'),
        ),
    ]
