# Generated by Django 3.2.3 on 2021-06-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_classinfo_student_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='level',
        ),
        migrations.AddField(
            model_name='classinfo',
            name='lop',
            field=models.CharField(default='', max_length=10, verbose_name='Lớp'),
        ),
    ]
