# Generated by Django 3.2.3 on 2021-06-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_alter_classinfo_sex_require'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='district',
            field=models.CharField(choices=[(None, 'Quận/Huyện'), ('Quận 1', 'Quận 1'), ('Quận 2', 'Quận 2'), ('Quận 3', 'Quận 3'), ('Quận 4', 'Quận 4'), ('Quận 5', 'Quận 5'), ('Quận 6', 'Quận 6'), ('Quận 7', 'Quận 7'), ('Quận 8', 'Quận 8'), ('Quận 9', 'Quận 9'), ('Quận 10', 'Quận 10'), ('Quận 11', 'Quận 11'), ('Quận 12', 'Quận 12'), ('Bình Chánh', 'Bình Chánh'), ('BTan', 'Bình Tân'), ('BThanh', 'Bình Thạnh'), ('CG', 'Cần Giờ '), ('CC', 'Củ Chi'), ('HM', 'Hóc Môn'), ('NB', 'Nhà Bè'), ('PN', 'Phú Nhuận'), ('TP', 'Tân Phú'), ('TB', 'Tân Bình'), ('TD', 'Thủ Đức')], max_length=10, verbose_name='Tên quận'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='sex_require',
            field=models.CharField(choices=[(None, 'Yêu cầu về giới tính người dạy'), ('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Yêu cầu về giới tính'),
        ),
    ]
